Repository ansible/ansible-zuul-jobs, pull requests merged in 2022-01, with the labels that each got.

#1269 add unit tests for community.okd collection
  zuul.d/ansible-cloud-jobs.yaml
  zuul.d/project-templates.yaml
Labels: gate

#1279 vcenter: don't reuse cached files
  playbooks/ansible-cloud/vcenter-appliance/pre.yaml
  roles/vmware-ci-nfs-share/tasks/main.yaml
Labels: gate

#1278 vcenter-appliance: no more controller group
  playbooks/ansible-cloud/vcenter-appliance/pre.yaml
  zuul.ansible.d/nodesets.yaml
Labels: gate

#1281 vcenter: don't run configure-swap
  playbooks/ansible-cloud/vcenter-appliance/pre.yaml
Labels: gate

#1280 include is deprecated, use include_tasks
  roles/configure-mirrors-fork/tasks/main.yaml
  roles/configure-mirrors-fork/tasks/mirror.yaml
  roles/configure-swap/tasks/main.yaml
Labels: gate

#1282 sanity: use a mirror to pull the test container
  roles/ansible-test/tasks/init_test_options.yaml
Labels: gate

#1283 community.okd - bump version to kubernetes.core 2.2.2
  zuul.d/project-templates.yaml
Labels: gate

#1286 ansible-test: get pip tp use /var/tmp as tmp dir
  roles/ansible-test/tasks/init_collection.yaml
Labels: gate

#1284 c.vmware: drop 2.9 and 2.10 sanity tests
  zuul.d/project-templates.yaml
Labels: mergeit

#1285 ansible-test-splitter needs git
  playbooks/ansible-test-splitter/pre.yaml
  zuul.d/ansible-cloud-jobs.yaml
Labels: gate, mergeit

#1287 ansible-test-base: also use /var/tmp
  playbooks/ansible-test-base/pre.yaml
Labels: mergeit

#1288 ansible-test: typo the second SF provider is ansible-limestone
  roles/ansible-test/tasks/init_test_options.yaml
Labels: mergeit

#1289 k8s: also call pip with TMPDIR=/var/tmp/ansible-test-pip
  playbooks/ansible-cloud/k8s/pre.yaml
Labels: mergeit

#1290 ansible-test: don't use the mirror with limestone
  roles/ansible-test/tasks/init_test_options.yaml
Labels: mergeit

#1291 nfs: adjust the ownership of the vms directory
  roles/vmware-ci-nfs-share/tasks/main.yaml
Labels: mergeit

#1293 ansible-test: mirror should already be enabled
  roles/ansible-test/tasks/init_test_options.yaml
Labels: mergeit

#1294 Set paramiko version to 2.8.1
  requirements.txt
Labels: mergeit

#1303 c.vmware: turn govcsim voting again
  zuul.d/project-templates.yaml
Labels: mergeit

#1306 introduce the ansible-ee-tests template
  playbooks/ansible-ee/pre.yaml
  playbooks/ansible-ee/run.yaml
  zuul.d/ee-jobs.yaml
  zuul.d/project-templates.yaml
Labels: mergeit

#1310 sf/ansible-tox-linters: use a container
  zuul.ansible.d/nodesets.yaml
  zuul.d/jobs.yaml
  zuul.sf.d/nodesets.yaml
Labels: mergeit

#1311 cloud.common needs kubernetes.core
  zuul.d/project-templates.yaml
Labels: mergeit

#1314 use SF to manage ansible-zuul-jobs
  zuul.sf.d/project.yaml
Labels: mergeit

#1313 deploy-artifacts: avoid the use of ansible_user_dir
  playbooks/ansible-galaxy-importer/run.yaml
  roles/deploy-artifacts/tasks/main.yaml
Labels: mergeit

#1312 sf: move more tox jobs in containers
  zuul.ansible.d/nodesets.yaml
  zuul.d/jobs.yaml
  zuul.sf.d/nodesets.yaml
Labels: mergeit

#1316 run ansible-test-splitter on container
  playbooks/ansible-test-splitter/run.yaml
  zuul.d/ansible-cloud-jobs.yaml
  zuul.sf.d/nodesets.yaml
Labels: mergeit

#1317 project: do not test with ansible-tox-py39-fedora
  zuul.sf.d/project.yaml
Labels: mergeit

#1320 Remove JUNOS stable-211 jobs from netcommon
  zuul.d/project-templates.yaml
Labels: mergeit

#1319 Update project-templates.yaml
  zuul.d/project-templates.yaml
Labels: mergeit

#1321 ansible-ee: define jobs for openvswitch
  playbooks/ansible-ee/pre-integration.yaml
  playbooks/ansible-ee/pre.yaml
  playbooks/ansible-ee/run-integration.yaml
  playbooks/ansible-ee/run-sanity.yaml
  playbooks/ansible-ee/run-unit.yaml
  playbooks/ansible-ee/run.yaml
  playbooks/ansible-network-openvswitch-appliance/files/bootstrap.yaml
  playbooks/ansible-network-openvswitch-appliance/pre.yaml
  playbooks/ansible-network-openvswitch-appliance/run.yaml
  zuul.d/openvswitch-openvswitch-jobs.yaml
  zuul.d/project-templates.yaml
  zuul.sf.d/nodesets.yaml
  zuul.sf.d/project.yaml
Labels: mergeit
